### ISSUE TITLE
Extra button

### ISSUE THREAD

**Issue by DrewNeon** [ramonrietdijk/livewire-tables#58]
Excuse me, is there a way to add a button within the bar above the table, preferablly on the upper right corner before other buttons, like shown below?

![addbutton](https://github.com/ramonrietdijk/livewire-tables/assets/25809783/12342d13-7917-4d95-ab13-8e46ae103d5d)

**Comment by ramonrietdijk** [comment]
Hi @DrewNeon!

Buttons in the top bar are set and shown depending on various conditions. There is no way to dynamically add additional buttons via the Livewire Table class itself. You can however [publish](https://ramonrietdijk.github.io/livewire-tables/getting-started/installation.html#publishing-views) the views of the package in order to add them yourself. See the [bar.blade.php](https://github.com/ramonrietdijk/livewire-tables/blob/3.x/resources/views/bar/bar.blade.php) file to see how it is built up.

Do note that you can add as many [actions](https://ramonrietdijk.github.io/livewire-tables/usage/actions.html) as you need in the dropdown, as an alternative.

Hope this helps!

**Comment by DrewNeon** [comment]
Thanks for the swift reply! Yeah, I've learned how to add items to the dropdown. I'd like to have a distinguished button, but seems impossible currently. 😫  And I don't want to mess up your blades so far.

**Comment by ramonrietdijk** [comment]
This package has been made with customizability in mind, so feel free to make any changes necessary! :wink:
